import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import 'swiper/css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
     <body className="overflow-x-hidden">
        <Header/>
        {children}
      </body>
    </html>
  );
}
